### ISSUE TITLE
1317	   As long as traffic filtering rules are restricted to match the

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#104]
1317	   As long as traffic filtering rules are restricted to match the
1318	   corresponding unicast routing paths for the relevant prefixes, the
1319	   security characteristics of this proposal are equivalent to the
1320	   existing security properties of BGP unicast routing.  However, this
1321	   document also specifies traffic filtering actions that may need
1322	   custom additional verification on the receiver side.  See Section 14.

[major] In general, Flow Specifications have a one-AS-hop propagation model, right?  This means that the security properties are different because (1) unicast routing propagates multiple hops, and (2) the intent of the "Route Origin ASN" (rfc6811) is not reflected in the request to rate-limit, or even drop (!) traffic to a destination.  Yes, it is all based on trust...but different.  For example, Origin Validation wouldn't be available for Flow Specifications.

**Comment by stoffi92** [comment]
I think this may be easy to answer. My personal opinion:
(1) no - there is no one-AS-hop propagation model
(2) since FS verification is tied to unicast routing origin validation indirectly is part of the picture.

Robert: this is for you ;-) (I will give you some more of the verification/validation cases)

**Comment by raszuk** [comment]
I agree that FS is never of one-AS-hop propagation model. That is why I voted to keep all extensions under different SAFI as now putting it all together broke basic prefix DDOS application and today sending it across internet will be far more difficult if not more insecure as possible. Not to mention that most of recent extensions makes sense only under the same administrative domain boundary. 

But apparently I am loosing that battle :(. 

To the very question of the Origin Validation it is all integrated by original design. That means that if I must validate received FS routes against unicast prefix and that unicast prefix was already Origin Validated that implies that FS is also Origin Validated without adding any new ROAs.  The problem starts when validation is getting disabled as this has avalanche effect for entire security model. 

Again while I understand that locally injected extensions would not need nor be able to be validated I think we lack ability to disable validation partially only for those.

**Comment by stoffi92** [comment]
//doc
FS is never of one-AS-hop propagation model.
To the very question of the Origin Validation it is all integrated by original design. That means that if I must validate received FS routes against unicast prefix and that unicast prefix was already Origin Validated that implies that FS is also Origin Validated without adding any new ROAs. The problem starts when validation is getting disabled as this has avalanche effect for entire security model.
