### ISSUE TITLE
Performing of actions if not all can be applied

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#119]
I found something that is in the Document and seems to be a remain from the *very*strict* Traffic Filtering Action:   

```
   Multiple traffic actions defined in this document may be present for
   a single NLRI.  If not all of them can be processed the filter SHALL
   NOT be applied at all.  For example: If for a given Flow
   Specification there are the action communities traffic-rate-bytes
   (0x8006) and traffic-marking (0x8009) attached, and the platform does
   not support one of them, none of the actions shall be applied.

```
This is actually a little contradicting with the considerations on Traffic Action Interference:

```
7.6.  Considerations on Traffic Action Interference

   Since traffic actions are represented as BGP extended community
   values, traffic actions may interfere with each other (e.g. there may
   be more than one conflicting traffic-rate-bytes action associated
   with a single Flow Specification).  Traffic action interference has
   no impact on BGP propagation of flow filters (all communities are
   propagated according to policies).

   If a flow filter associated with interfering flow actions is selected
   for packet forwarding, it is a implementation decision which of the
   interfering traffic actions are selected.  Implementors of this
   specification SHOULD document the behaviour of their implementation
   in such cases.
```

Because the one on top says “if you have multiple Actions and you cannot perform all of them, do not apply and Action” (not making any exceptions for interfering actions) , and the second simply says “let the implementation resolve that, and document it”

I think the top paragraph should refer to interfering actions and let the implementation decide.

**Comment by suehares** [comment]
The problem with the implementation deciding what happens with the actions is
shown as follows: 
 
1) filter1 - redirect2 
2) filter1 - drop

If filter 1 say direct and drop, what you do. 
Our indication states, do not do anything (let everything pass) 
The text in 7.6 states implementation specific, 
let the implementation decide. 

This gives you inconsistent behavior for filtering in the AS.

**Comment by stoffi92** [comment]
> 1. filter1 - redirect2
> 2. filter1 - drop

Actually with these 2 filters I do not have too much of a problem, because it is a "edge case" of 

1. filter1 - redirct2
2. filter1 - rate-limit

Which is  rate-limit the traffic and redirect the rest. (Obviously there is not so much to redirect when you rate-limit to 0).

My concern is more:

1. filter1: drop
2. filter1: rate-limit

In that case it is implementation dependend what is going to happen. 

The draft gives general advice to operators to use additional mechanisms like the BGP-policy-frameworks (route-map and such) to make the result predictable where needed.

**Comment by suehares** [comment]
Policy will decide the preference is your answer. 
This policy must clearly be specified and queried.
