### ISSUE TITLE
Specify the afi/safi against which we run the validation

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#121]
See stoffi92/draft-ietf-idr-flow-spec-v6#1 - I think the afi/safi that should be used for validation should be incooperated into rfc5575bis and only the ipv6 specific work needs to go into draft-ietf-idr-flow-spec-v6.

**Comment by stoffi92** [comment]
This is the text in flow spec v6 I refer to ... I would like to work that change in rfc5575bis (this makes less noise in the extension, seems clean and is something that is missing in rfc5575bis anyway:

```
 This document will redefine the [I-D.ietf-idr-rfc5575bis] SAFIs in
   order to make them AFI specific and applicable to both IPv4 and IPv6
   applications.

   The following changes are defined:

      "SAFI 133 for IPv4 dissemination of flow specification rules" to
      now be defined as "SAFI 133 for dissemination of unicast flow
      specification rules"

      "SAFI 134 for VPNv4 dissemination of flow specification rules" to
      now be defined as "SAFI 134 for dissemination of L3VPN flow
      specification rules"

   For both SAFIs the indication to which address family they are
   referring to will be recognized by AFI value (AFI=1 for IPv4 or
   VPNv4, AFI=2 for IPv6 and VPNv6 respectively).  Such modification is
   fully backwards compatible with existing implementation and
   production deployments.

```

**Comment by stoffi92** [comment]
@raszuk have a look - I think it is better suited here (since we want to cleanup things here anyway)

**Comment by raszuk** [comment]
So I have a question ... can implementation claim compliance to RFC5575bis
when it supports only IPv6 or only IPv4 AFI and not both ?

Thx,
R.

**Comment by stoffi92** [comment]
An implementation of IPv4 flowspec can *only* clame to be RFC5575bis compliant (because they implement the SAFI=133 (maybe not only 134) under AFI=1 (which is not completely specified in RFC5575bis currently - but should be done anyway). 

An implementation of IPv6 flowspec *only* implements the same SAFIs but *only* under AFI=2. So it is not rfc5575bis compliant (even though they still need to implement a large percentage of what is in rfc5575bis), but flow-spec ipv6 draft compliant.

If the implementation supports SAFI=133, 134 with AFI=1, 2 it is rfc5575bis + flow-spec ipv6 draft
compliant.

**Comment by stoffi92** [comment]
@raszuk: ah. there is a little more changes required in rfc5575bis, because we also need to put the AFI=1 in rfc5575bis and which AFI/SAFI the validations run against. I will show you the change for review. We can roll it back if it does not fit there. But I think there is a "hole" in the rfc5575bis anyway, because it is not defining the AFI=1 anywhere, while all implementations implicitly assumed AFI=1

**Comment by raszuk** [comment]
Well it talks explicitly about IPv4 so this is AFI 1 without any doubts :)

**Comment by stoffi92** [comment]
correct - just noticed.
