### ISSUE TITLE
Security section changes 

### ISSUE THREAD

**Issue by suehares** [stoffi92/rfc5575bis#129]
After reading Robert's comment this morning, I realized I wanted to warn the IESG that the IDR work is not completed on the securing of this topic.   I am frustrated with Alvaro's middle ground that rewrites the introductorty text substantially while not admitting that we still have more security issues.  After I read Robert's comment, I think a tutorial on the state of IDR's work is better left outside this document.  

Thank you Robert for being the voice of sanity. 
 
if the text regarding [I-D.ietf-idr-bgp-flowspec-oid] is still includced in the document,  then the last sentence is 
Specifications relaxing the validation should contain security considerations that provide details on the required additional filtering.

old/required additional filtering/ 
new/ required additional filtering and filtering mechanisms.  For example, the use of RFC6811
   to enhance filtering within an AS confederation./

**Comment by stoffi92** [comment]
@raszuk @suehares please advise.
 
I changed the Introduction to contain @suehares text as of #6: 

```
 The flow specification received from an internal BGP peer within the same autonomous system
    (per <xref target="RFC4271" />) is assumed to have been validated prior
    to transmission within the iBGP mesh of an autonomous system.
```

Now the security considerations reads as:

```
    One proposal for relaxing the above mechanisms within the administrative
    boundaries of an AS via iBGP is included in <xref target="I-D.ietf-idr-bgp-flowspec-oid" />.
    Deployment of such specific relaxations of the validation within an
    administrative boundary of a network, defined by an AS or an
    AS-Confederation boundary,

```
Why does flowspec-oid need to relax iBGP validation when the introduction of rfc5575bis states that iBGP is assumed to be "validated" already? I am not sure if the change that I did in #6 is consistent.

I would like to remove the FS OID paragraph entirely (but this has been added recently as suggested by @suehares in #62).

**Comment by stoffi92** [comment]
Since I am unhappy with the reference to flowspec-oid I removed the reference and made the paragraph more general:

```
    Deployment of specific relaxations of the validation within an
    administrative boundary of a network, defined by an AS or an
    AS-Confederation boundary, may be useful in some networks for
    quickly distributing filters to prevent denial-of-service attacks.
    For a network to utilize this relaxation, the BGP policies must
    support additional filtering since the origin AS field is empty.
    Specifications relaxing the validation restrictions SHOULD
    contain security considerations that provide details on the
    required additional filtering. For example, the use of
    <xref target="RFC6811" /> to enhance filtering within an AS
    confederation.

```
