### ISSUE TITLE
remove the references to section 1.1 and 1.2 in section 5

### ISSUE THREAD

**Issue by suehares** [stoffi92/rfc5575bis#130]
section 5, paragraph 1
Delete /Section 1.1 and Sectino 1.2 explain details on the limitations of previous mechanisms
and why Flow Specifications provides a solution to prevent DOS and aid BGP/MPLS filtering rules. / 

section 5, paragraph 2 - Editorial changes needed to clean up grammar in following paragraph 
after the sentence is removed.  
old/The Flow Specification defined above to convey information/ 
new/The Flow Specification defined in section 4 conveys information/

**Comment by stoffi92** [comment]
section 5 paragraph 1 was removed already in #128

**Comment by stoffi92** [comment]
Closed in 867365543d9f365f0832293cebd72d13ed28ff1c
