### ISSUE TITLE
IESG Barry Leiba: Abstract ie/ig

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#175]
— Abstract —

   Other applications (ie. centralized control of traffic in a SDN or
   NFV context) are also possible.

I don’t think you mean “i.e.” here, but “e.g.”  I would avoid the Latin (for exactly this reason: many people don’t understand it and misuse it) and say, “Other applications, such as centralized control of traffic in an SDN or NFV context, are also possible.”

**Comment by suehares** [comment]
old/Other applications (ie. centralized control of traffic in a SDN or
NFV context) are also possible./
new/ther applications (e.g. centralized control of traffic in a SDN or
NFV context) are also possible./ 

This is the appropriate change.
