### ISSUE TITLE
IESG Benjamin Kaduk: inconsistent NLRI Validation VPN-NLRI

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#184]
There might be a minor internal inconsistency to tidy up (or I might be
misunderstanding things).  Section 8 states that:

   Contrary to the behavior specified for the non-VPN NLRI, Flow
   Specifications are accepted by default, when received from remote PE
   routers.

As far as I can tell, this is referring to the text in Section 6 where (for
the non-VPN case) "By default a Flow Specification NLRI MUST be validated
such that it is considered feasible if and only if all of the below is true
[...]".  But immediately following what I quote above is a statement that
"the validation proceure (section 6) [...] [is] the same as for IPv4", which
seems to be in conflict with this statement ("contrary to" vs. "the same
as").

**Comment by stoffi92** [comment]
This is related to #1022

**Comment by suehares** [comment]
Based on RR comment from Robert, I believe the current text is correct.  
We have agreed in email so I think we can close this one.

**Comment by suehares** [comment]
Christoph - I am closing per your comment.
