### ISSUE TITLE
IESG Benjamin Kaduk: Abstract

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#185]
The Abstract is perhaps pushing the length limits appropriate for an
Abstract (vs. Introduction).

Abstract

   Additionally, it defines two applications of that encoding format:
   one that can be used to automate inter-domain coordination of traffic
   filtering, such as what is required in order to mitigate
   (distributed) denial-of-service attacks, and a second application to

This makes me think of the DOTS WG (but it's far from clear that we should
reference it in this text).

**Comment by suehares** [comment]
agree with will not fix tag.

**Comment by stoffi92** [comment]
//doc 
Not changed.
