### ISSUE TITLE
IESG Benjamin Kaduk: Section 1 - comma

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#186]
Section 1

   This document obsoletes "Dissemination of Flow Specification Rules"
   [RFC5575], the differences can be found in Appendix B.  This document

nit: comma splice

**Comment by suehares** [comment]
This does need to change 
New /This document obsoletes the "Dissemination of Flow Specification Rules" [RFC5575] 
(see Appendix B for the differences).  This document/

**Comment by stoffi92** [comment]
//doc
New /This document obsoletes the "Dissemination of Flow Specification Rules" [RFC5575]
(see Appendix B for the differences). This document/
