### ISSUE TITLE
IESG Benjamin Kaduk: Validation Question

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#187]
A Flow Specification received from an external autonomous system will
   need to be validated against unicast routing before being accepted
   (Section 6).  The Flow Specification received from an internal BGP
   peer within the same autonomous system [RFC4271] is assumed to have
   been validated prior to transmission within the internal BGP (iBGP)
   mesh of an autonomous system.  If the aggregate traffic flow defined

(Just to check, there's no particular harm in also validating iBGP
flowspecs, just the extra computation burden of doing so, right?)

**Comment by suehares** [comment]
agree wont fix.

**Comment by stoffi92** [comment]
//doc
There is no real need to validate updates from a trusted source, which is the own administrative domain in that case.
