### ISSUE TITLE
IESG Benjamin Kaduk: Robustness of Automated Systems

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#188]
systems that are able to detect malicious traffic flows.  When
   automated systems are used, care should be taken to ensure their
   correctness as well as the limitations of the systems that receive
   and process the advertised Flow Specifications (see also Section 12).

This seems to discuss making sure that the recipients of automated
information handle it robustly; is it also worth some considerations on
robustness of generating such automated information (something akin to a
circuit breaker that would shut off the source if it started producing
nonsensical output)?
Also, nit: I think I parse this as "care should be taken to ensure [...] the
limitations of the systems that receive and process [flowspecs]", which
doesn't quite seem like what was intended.

**Comment by suehares** [comment]
nit - should be fixed 
New/ When automated sytems are used, care should be taken 
to ensure the correctness of the automated system and 
the limit of the system when processing the advertised Flow Specification
(see also Section 12)./

Robert might want to weigh in on this comment.

**Comment by stoffi92** [comment]
New:
   When automated systems are used, care should be taken
   to ensure the correctness of the automated system. The
   the limitations of the receiving systems that need to process
   these automated Flow Specifications 
   need to be taken in consideration as well.
