### ISSUE TITLE
IESG Benjamin Kaduk: Section 4.2.1.1, 4.2.1.2

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#191]
Section 4.2.1.1, 4.2.1.2

While I don't anticipate needing a future extension to numeric_op, having
the '0' field only be "SHOULD be set to 0" (vs. "MUST") seems to hamper any
future extensibility efforts.
(Similarly for the "Traffic-action" field in Section 7.3, and
"Traffic-marking" from Section 7.5.)

**Comment by suehares** [comment]
The text that states:  "SHOULD be set to 0 on NLRI encoding, and MUST be ignored during
      decoding"

is actually used for extensibility.  The set to zero indicates that sending should be a know state, and the receiver ignores all the settings. 

My recommendation is to leave the text as is.  After Robert and Christoph sees my answer, we can close this one.

**Comment by stoffi92** [comment]
//doc 
The text that states: "SHOULD be set to 0 on NLRI encoding, and MUST be ignored during
decoding"

is actually used for extensibility. The set to zero indicates that sending should be a know state, and the receiver ignores all the settings.
