### ISSUE TITLE
343	   All combinations of component types within a single NLRI are allowed,

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#20]
343	   All combinations of component types within a single NLRI are allowed,
344	   even if the combination makes no sense from a semantical perspective.
345	   If a given component type within a prefix in unknown, the prefix in
346	   question cannot be used for traffic filtering purposes by the
347	   receiver.  Since a Flow Specification has the semantics of a logical
348	   AND of all components, if a component is FALSE, by definition it
349	   cannot be applied.  However, for the purposes of BGP route
350	   propagation, this prefix should still be transmitted since BGP route
351	   distribution is independent on NLRI semantics.

[nit] s/prefix in unknown/prefix is unknown

[nit] s/independent on NLRI/independent of NLRI

[major] "...for the purposes of BGP route propagation, this prefix should still be transmitted since BGP route distribution is independent on NLRI semantics."  I think this is a vulnerability: a (large) set of meaningless Flow Specifications may be injected in the routing system...

[major] Also, propagating these unknown components may result in a router down the line, which understands them, reacting.  While the reaction shouldn't result in reset adjacencies, it may result in inconsistent forwarding or other unexpected outcomes...

[major] This treatment of unknown extensions is in conflict with the text in §11.  See my comments there.

**Comment by stoffi92** [comment]
#20, and #93 are related - this paragraph should be repaired
This should be fixed in this paragraph: "343 All combinations of component types within a single NLRI are allowed"

**Comment by stoffi92** [comment]
This is a remain from the "old days" when FS should be opaque to BGP. In such an environment BGP has no understanding of components. Since the implementations do not treat the NLRI opaque the WG voted against this idea. Now BGP knows about components and is able to throw away useless combinations. 

OLD:
   All combinations of component types within a single NLRI are allowed, even
   if the combination makes no sense from a semantical perspective.
   If a given component type within a prefix in unknown, the prefix in
   question cannot be used for traffic filtering purposes by the
   receiver. Since a Flow Specification has the semantics of a logical
   AND of all components, if a component is FALSE, by definition it
   cannot be applied. However, for the purposes of BGP route
   propagation, this prefix should still be transmitted since BGP route
   distribution is independent on NLRI semantics.

NEW:
     All combinations of component types within a single NLRI are allowed. However,
       some combinations cannot match any packets (ie. "ICMP Type AND Port" will never
       match any packets), and thus SHOULD not be propagated.

**Comment by stoffi92** [comment]
Robert - can you please review this change - is this reasonable (I think this was only a remain from when I thought FS should be opaque to BGP)

**Comment by raszuk** [comment]
Well I am very conservative here. If I do not recognize part of NLRI and can not validate NLRI both semantically and syntactically I must not propagate it. NLRI is not and should never be opaque as NLRI is the BGP database key. 

Moreover if I have no assurance my peer understands given NLRI I should never propagate it to him. That is why IMHO for all practical purposes and lack of dynamic capabilities any change to NLRI requires new SAFI.

**Comment by stoffi92** [comment]
What I proposed above your comment seems fit into your answer:

1) unknown flow components / NLRI that are not understood completely lead to treat-as-withdraw (and thus are not propagated) -> error handling. NLRI opaque has completely been removed from the draft.
2) New SAFIs are not part of the draft and if one chooses to use a new safi for a FS extension this is fine.

**Comment by raszuk** [comment]
Agreed.

**Comment by stoffi92** [comment]
//doc
Only filters that actually can match packets should be propagated, unknown components will not be propagated see the updated paragraph about FS extensions.
