### ISSUE TITLE
IESG Benjamin Kaduk: Security BGP

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#208]
As long as Flow Specifications are restricted to match the
   corresponding unicast routing paths for the relevant prefixes
   (Section 6), the security characteristics of this proposal are

[There's an implicit "and both are received over trustworthy channels" in
here.  Perhaps it's okay to remain implicit, given how well-known BGP's
security properties are...]

**Comment by suehares** [comment]
I think you can close this one.
