### ISSUE TITLE
IESG Benjamin Kaduk: Security relaxing validation

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#209]
Where the above mechanisms are not in place, this could open the door
   to further denial-of-service attacks such as unwanted traffic
   filtering, remarking or redirection.

nit(?): I might just say "In particular, relaxing the validation procedure
could [...]".

**Comment by suehares** [comment]
I would leave this as certain people really wanted this text. 
I think you can close this.
