### ISSUE TITLE
IESG Benjamin Kaduk: Security incomplete sentence

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#210]
additional filtering.  For example, the use of [RFC6811] to enhance
   filtering within an AS confederation.

nit: incomplete sentence.

**Comment by suehares** [comment]
change the following text above this:
   Old/Deployment of specific relaxations of the validation within an
   administrative boundary of a network, defined by an AS or an AS-
   Confederation boundary, may be useful in some networks for quickly
   distributing filters to prevent denial-of-service attacks./
New:/Deployment of specific relaxations of the validation within an
   administrative boundary of a network  are useful in some networks for quickly
   distributing filters to prevent denial-of-service attacks./  
Then
change the text to: 
New/For example, the use of Origin validation can provide 
enhanced filtering within an AS confederation./

Ben's correct the paragraph needs more aid.

**Comment by stoffi92** [comment]
//doc
Solved as of Sue's comment.
