### ISSUE TITLE
IESG Benjamin Kaduk: Security stresses receiving systems

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#213]
Flow Specification BGP speakers (e.g. automated DDoS controllers) not
   properly programmed, algorithms that are not performing as expected,
   or simply rogue systems may announce unintended Flow Specifications,
   send updates at a high rate or generate a high number of Flow
   Specifications.  This may stress the receiving systems, exceed their
   maximum capacity or may lead to unwanted Traffic Filtering Actions
   being applied to flows.

Is there any relevant guidance to give to receiving systems?

**Comment by suehares** [comment]
After you put in Barry's comment, the only addition is.  
"Implementers of flow specification need to be aware of 
system-resource issues." 

Again - ask Robert if this will be helpful.

**Comment by stoffi92** [comment]
@raszuk can you please comment on this.

**Comment by stoffi92** [comment]
//doc 
Not even the BGP spec says a word about what implementation should do when under stress or run out of FIB. This may not help to put it in FS
