### ISSUE TITLE
IESG Benjamin Kaduk: Appendix A Python

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#214]
Appendix A

I don't know that just this one function is useful without some description
of what format of input it requires.  For example, if a.components and/or
b.components have elements that evaluate to "false", the first two checks
could return incorrect results (the perhaps-more-obvious case where both
comp_a and comp_b are None cannot happen due to the nature of zip_longest).

**Comment by suehares** [comment]
RFC 5575bis had this information.  
I think we need to add some descriptions but I'm not sure what to do. 
Maybe you could ask your friends implementing this what is helpful.

**Comment by stoffi92** [comment]
I think what can be done is adding comments that explain the nature of the input variables. I do not think that the code itself is normative. It is illustrating the behaviour already explained in Section 5.1.

**Comment by stoffi92** [comment]
//doc
Added the full example python module that also gives usage examples of the compare code.
