### ISSUE TITLE
IESG Benjamin Kaduk: Appendix B

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#215]
Appendix B

      Section 7 defines all Traffic Filtering Action Extended
      communities as transitive extended communities.  [RFC5575] defined
      the traffic-rate action to be non-transitive and did not define
      the transitivity of the other Traffic Filtering Action communities
      at all.

I assume the consequences of changing a community from non-transitive to
transitive are well-known (but not to me) and that any operational
considerations for mixed deployments are already stated somewhere prominent
to someone working with BGP.  (Where is that?)

      Section 7.7 contains general considerations on interfering traffic
      actions.  Section 7.3 also cross-references this section.

nit(?): the last "this section" refers to 7.7, not the location of the text
I'm quoting from (Appendix B).  I misread it the first time.

**Comment by suehares** [comment]
We need to fix the reference for 7.3 - I think.   
The other point about transitive versus non-transitive - I will send to Ben. 

Last Comment!!

**Comment by stoffi92** [comment]
//doc
Transitive vs non-transitive: The IANA assigned extended community is from the transitive pool of extended communities. The text in RFC5575 is ignoring this fact. The major implementations treat it as transitive.
