### ISSUE TITLE
IESG Warren Kumari: Modern IP routers contain both the capability

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#216]
“ Modern IP routers contain both the capability to forward traffic according to
IP prefixes ...” For some reason the “according to IP prefixes” scans oddly to
me - the rest of the actions are also (largely) “according to ip prefixes” -
this is more of a nit / preference, but I think it would be better to just drop
that phrase.

**Comment by suehares** [comment]
Old/ Modern IP routers contain both the capability to forward traffic
   according to IP prefixes as well as to classify, shape, rate limit,
   filter, or redirect packets based on administratively defined
   policies./
New /
   Modern IP routers contain both the capability to forward traffic
   as well as to classify, shape, rate limit,
   filter, or redirect packets based on administratively defined
   policies.  /

This is a suggested change per Warren's comment

**Comment by stoffi92** [comment]
//doc
Changed as suggested.
