### ISSUE TITLE
IESG Warren Kumari: removed all references to a opaque-key

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#217]
“ This      specification has removed all references to a opaque-key property. 
   BGP is able to understand the NLRI encoding.” 2 nits: 1: a opaque-key -> an
opaque-key (or the opaque-key) 2: BGP is able to... seems a bit odd - BGP is
just a protocol, it doesn’t really understand *anything*. I think that a better
option would be best “BGP implementations are”. Again this is just a nit, feel
free to address it or not...

**Comment by suehares** [comment]
the change from 
/a opaque-key/  to /an opaque-key/ - is good 
/BGP is able/ to /BGP implementations are/ is good

**Comment by suehares** [comment]
Do you want me to leave this open until you've changed the text?

**Comment by stoffi92** [comment]
//doc 
/a opaque-key/ to /an opaque-key/
/BGP is able/ to /BGP implementations are/
