### ISSUE TITLE
IESG Éric Vyncke: ipv6 ? draft-ietf-idr-flow-spec-v6 

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#219]
Thank you for the work put into this document. The document is clear, easy to read (I appreciated the given examples). 

Alas, due to overload of work, I had only a quick browse through the document with specific focus points and found nothing EXCEPT why having two different documents ? One for IPv4 (with the core elements of the protocol) and one for IPv6 (with only the IPv6 specifics)... I am more than surprized to say the least... hence my DISCUSS...

This blocking DISCUSS can easily be fixed: e.g., with a RFC Editor note to make a cluster of this document and draft-ietf-idr-flow-spec-v6 so that they are published together with adjacent RFC numbers. Merging the two documents would be preferred but I understand that this is more work (albeit a missed opportunity).

Please find below a couple on non-blocking COMMENTs.

I hope that this helps to improve the document,

Regards,

-éric

**Comment by suehares** [comment]
Hoping v6 draft will be ready shortly.   
Alvaro Retana has agreed this is a won't fix
