### ISSUE TITLE
IESG Robert Wilton: 4.2.  NLRI Value Encoding

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#222]
4.2.  NLRI Value Encoding

   Components MUST follow strict type ordering by increasing numerical
   order.  A given component type may (exactly once) or may not be
   present in the Flow Specification.  If present, it MUST precede any
   component of higher numeric type value.

I wasn't sure, but wondering whether "may (exactly once) or may not be" should be "MAY (exactly once) be"?

**Comment by stoffi92** [comment]
@suehares I think what Robert suggests is easier to read then the current version. Change?

**Comment by suehares** [comment]
I agree that what Robert has suggested is better. 
Here's the new from what I read: 

New/ Components MUST follow strict type ordering by increasing numerical
order. A given component type MAY (exactly once) or may not be
present in the Flow Specification. If present, it MUST precede any
component of higher numeric type value./

**Comment by stoffi92** [comment]
I suggest to remove the "or may not":

New/ Components MUST follow strict type ordering by increasing numerical
order. A given component type MAY (exactly once) be
present in the Flow Specification. If present, it MUST precede any
component of higher numeric type value./

**Comment by suehares** [comment]
I’m fine with that text. 

 

Sue

**Comment by stoffi92** [comment]
//doc 
Fixed as suggested.
