### ISSUE TITLE
IESG Robert Wilton: 5.1.  Ordering of Flow Specifications

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#223]
5.1.  Ordering of Flow Specifications

   For all other component types, unless otherwise specified, the
   comparison is performed by comparing the component data as a binary
   string using the memcmp() function as defined by [ISO_IEC_9899].  For
   strings with equal lengths the lowest string (memcmp) has higher
   precedence.  For strings of different lengths, the common prefix is
   compared.  If the common prefix is not equal the string with the
   lowest prefix has higher precedence.  If the common prefix is equal,
   the longest string is considered to have higher precedence than the
   shorter one.

I think that the intended comparison here is clear, but I was wondering whether this text should flag endian concerns at all.  E.g. if the component data has been stored in memory and any numeric values have had endian conversion performed on them then a naive memcmp() could give a different answer.

**Comment by suehares** [comment]
Christoph  or Robert - do you think we need to put any endian comments here? 
We have not in the past.  I'm too deeply engrained in that habit to be objective.

**Comment by raszuk** [comment]
Let's observe that endianess is global to a platform. So all data is
written in the same way to memory. That means that memcmp() would still
work fine irrespective of the endianess of the platform.

Let's also note that it is in the same time irrespective to the
endianess of the src of the data too.

So IMHO there is not much point to mention this here.

Thx,
R.

**Comment by suehares** [comment]
Ok – I did not miss something.  I will close the issue If you have not. 

 

Sue

**Comment by suehares** [comment]
per Roberts email - I did not miss anything.
