### ISSUE TITLE
Rob Wilton Discuss on "Should be set to Zero" 

### ISSUE THREAD

**Issue by suehares** [stoffi92/rfc5575bis#224]
Rpb Wilton's discuss: states 
I note that in 5 places this document has text that states the
equivalent to "SHOULD be set to 0 on encoding, and MUST be ignored
during decoding."
 (example given below).

Alvaro agreed that 
old/SHOULD be set to 0 on encoding,  and MUST be ignored
during decoding."/
new/SHOULD be set to 0 on encoding,  and MUST be ignored
during decoding."/

is a change that will be made only after Jie Dong (Shepherd) checks with all texts. 

I am assigning this to me - since I will flag when Jie Dong is done. 

--------
> > Example:
> >    The extended is encoded as follows:
> >
> >       0                   1                   2                   3
> >       0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
> >      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
> >      |   reserved    |   reserved    |   reserved    |   reserved    |
> >      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
> >      |   reserved    | r.|    DSCP   |
> >      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
> >
> >            Figure 6: Traffic Marking Extended Community Encoding
> >
> >    o  DSCP: new DSCP value for the transiting IP packet.
> >
> >    o  reserved, r.: SHOULD be set to 0 on encoding, and MUST be ignored
> >       during decoding.
> >

**Comment by suehares** [comment]
Just a reminder - we are waiting on Jie Dong's report prior to working on this issue.

**Comment by stoffi92** [comment]
This is the complete list of SHOULD - MUST constructs in the draft. I think not all of them need/should be changed in the document:

@suehares please review. 
```
4.  Dissemination of IPv4 Flow Specification Information
...
   This NLRI information is encoded using MP_REACH_NLRI and
   MP_UNREACH_NLRI attributes as defined in [RFC4760].  When advertising
   Flow Specifications, the Length of Next Hop Network Address SHOULD be
   set to 0.  The Network Address of Next Hop field MUST be ignored.
```

```
4.2.1.1.  Numeric Operator (numeric_op)
...
   a -  AND bit: If unset, the result of the previous {op, value} pair
      is logically ORed with the current one.  If set, the operation is
      a logical AND.  In the first operator octet of a sequence it
      SHOULD be encoded as unset and MUST be treated as always unset on
      decoding.  The AND operator has higher priority than OR for the
      purposes of evaluating logical expressions.

...
   0 -  SHOULD be set to 0 on NLRI encoding, and MUST be ignored during
      decoding
```

```
4.2.1.2.  Bitmask Operator (bitmask_op)

...
   0 - all 0 bits:  SHOULD be set to 0 on NLRI encoding, and MUST be
      ignored during decoding
```

```
4.2.2.12.  Type 12 - Fragment

...
   0 -  SHOULD be set to 0 on NLRI encoding, and MUST be ignored during
      decoding
```

```
7.3.  Traffic-action (traffic-action) sub-type 0x07
...
   o  Traffic Action Field: Other Traffic Action Field (see Section 11)
      bits unused in this specification.  These bits SHOULD be set to 0
      on encoding, and MUST be ignored during decoding.
```

```
7.5.  Traffic Marking (traffic-marking) sub-type 0x09
...
   o  reserved, r.: SHOULD be set to 0 on encoding, and MUST be ignored
      during decoding.

```

**Comment by suehares** [comment]
Jeff's comment states: (v1/V2)  
Regardless of the language, our desire is v1 leaves them as zero and pays no attention to them so that v2 can set them and v1 doesn't care.

I believe that all of your examples are correct.   It would be good to publish the revision to the authors, and to send a copy to Jeff, Jie and Alvaro.  

Thank you for your patience

**Comment by suehares** [comment]
Christoph - you can close this after creating the draft.

**Comment by stoffi92** [comment]
Alvaro:
Hi!

Going back to this thread…and in light of the discussion about the setting/use of the bits.  

I am disappointed that only Jeff replied. :-(   But happy that at least two implementations behave the same and ignore the received bits.  This makes me conclude that “MUST be ignored” is ok.

On the sending side, knowing that all send 0s, then let’s change to “MUST be set to 0”.


Jie:  If you don’t think this is a valid read of the thread, let me know.


Christoph:  If you don’t hear an objection in a couple of days, please go ahead with an update. :-)


Thanks!


Alvaro.
