### ISSUE TITLE
683	   The code below shows a Python3 implementation of the comparison

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#53]
683	   The code below shows a Python3 implementation of the comparison
684	   algorithm.  The full code was tested with Python 3.6.3 and can be
685	   obtained at https://github.com/stoffi92/flowspec-cmp [1].

[minor] I would prefer to see the code in an Appendix.

[major] We need to include template text about the licensing in the Code Component below.  Please take a look at the IETF Trust Legal Provisions and add the appropriate text: https://trustee.ietf.org/license-info/IETF-TLP-5.pdf

**Comment by stoffi92** [comment]
I agree moving this to the Appendix. 

Sue: Can you point me to a example RFC document were I can see what exactly I should put into the document and where? I wrote the code and it can be licenced under BSD2 or such.

**Comment by suehares** [comment]
My understanding is that you did not need an RFC reference.  If you need it, please let me by re-opening and assigning it to me.

**Comment by stoffi92** [comment]
Yes, I think I solved this in the meantime ;-)

**Comment by stoffi92** [comment]
//doc 
Moved the Python source to the Appendix and added a the licence in the code component.
