### ISSUE TITLE
852	   Some traffic action communities may interfere with each other.

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#66]
852	   Some traffic action communities may interfere with each other.
853	   Section 7.6 of this specification provides general considerations on
854	   such traffic action interference.  Any additional definition of a
855	   traffic actions specified by additional standards documents or vendor
856	   documents MUST specify if the traffic action interacts with an
857	   existing traffic actions, and provide error handling per [RFC7606].

[nit] s/definition of a traffic actions/definition of traffic actions

[major] "Any additional definition of a traffic actions specified by additional standards documents or vendor documents MUST specify..."  We really can't mandate what vendor documents say.   s/additional definition of a traffic actions specified by additional standards documents or vendor documents MUST specify/additional definition of a traffic action MUST specify

[major] "MUST specify if the traffic action interacts with an existing traffic actions"  I think you meant something like: "MUST specify the action to take if..."

[major] "Any additional definition of a traffic actions...MUST...provide error handling per [RFC7606]."  rfc7606 already indicates what to do about a malformed Extended Community attribute, which is how other actions would presumably be specified.   rfc7606 only mandates error specifications for new attributes.  What are your expectations here?

**Comment by stoffi92** [comment]
> [nit] s/definition of a traffic actions/definition of traffic actions
> 
> [major] "Any additional definition of a traffic actions specified by additional standards documents or vendor documents MUST specify..." We really can't mandate what vendor documents say. s/additional definition of a traffic actions specified by additional standards documents or vendor documents MUST specify/additional definition of a traffic action MUST specify

ack

> [major] "MUST specify if the traffic action interacts with an existing traffic actions" I think you meant something like: "MUST specify the action to take if..."

ok.
 
> [major] "Any additional definition of a traffic actions...MUST...provide error handling per [RFC7606]." rfc7606 already indicates what to do about a malformed Extended Community attribute, which is how other actions would presumably be specified. rfc7606 only mandates error specifications for new attributes. What are your expectations here?

due to the changes in the "error handling" section this can be removed, it seems to sufficiently defined in that other section.

**Comment by suehares** [comment]
Christoph: 

 

Going through these one at a time.   I did not respond in time for you consider these earlier.

**Comment by stoffi92** [comment]
//doc
Major1:
Removed the vendor documents and standard documents as suggested

Major2:
Changed as suggested

Major3: 
Due to the changes in the "error handling" section this can be removed, it seems to sufficiently defined in that other section.
