### ISSUE TITLE
937	7.4.  RT Redirect (rt-redirect) sub-type 0x08

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#76]
937	7.4.  RT Redirect (rt-redirect) sub-type 0x08
...
948	   It should be noted that the low-order nibble of the Redirect's Type
949	   field corresponds to the Route Target Extended Community format field
950	   (Type).  (See Sections 3.1, 3.2, and 4 of [RFC4360] plus Section 2 of
951	   [RFC5668].)  The low-order octet (Sub-Type) of the Redirect Extended
952	   Community remains 0x08 for all three encodings of the BGP Extended
953	   Communities (AS 2-byte, AS 4-byte, and IPv4 address).

[nit] I think that this whole paragraph is not needed....and it actually may confuse people.  I recommend deleting it.

**Comment by stoffi92** [comment]
Delete? This clearly is not *needed*.

**Comment by raszuk** [comment]
Yes I think it can be deleted. I checked RFC7674 and while it is there it does look it is there pretty much for informational purposes only and not functional reasons. So fell free to take it out.

**Comment by stoffi92** [comment]
I read over this and think some parts are needed to cover the encoding of the community. Added it again.
