### ISSUE TITLE
1022	   Flow Specification rules received via this NLRI apply only to traffic

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/rfc5575bis#85]
1022	   Flow Specification rules received via this NLRI apply only to traffic
1023	   that belongs to the VRF(s) in which it is imported.  By default,
1024	   traffic received from a remote PE is switched via an MPLS forwarding
1025	   decision and is not subject to filtering.

1027	   Contrary to the behavior specified for the non-VPN NLRI, flow rules
1028	   are accepted by default, when received from remote PE routers.

[major] The only other mention of "flow rule" is in the Introduction when referring to the validation of external Flow Specifications, which seems to then map to §6...but the next sub-section says that those procedures apply.  What am I missing?

**Comment by stoffi92** [comment]
Can you also read thru this (you may need to read a bit above/below the Text that Alvaro cited. Especially on the "those procedures apply" (last) part. (I think this is the last issue I need to cover - everything else is pretty much solved already).

**Comment by raszuk** [comment]
I am having a bit hard time to guess what the comment means ... 

Does it hint that section 6 should verbatim exclude validation for L3VPN routes assuming that L3VPN will always be managed by the same administrative domain ? 

I am just not sure which sub-section is the "next sub-section" :) ?

**Comment by stoffi92** [comment]
//doc
The term "flow rule" has been changed and Flow Specification is used in the entire document. This paragraph also mentions that in an MPLS network traffic from other PEs (L3-VPN) receive MPLS traffic and will not filter the traffic. Traffic needs to be filtered ingress between CE-PE not in the MPLS forwarding domain.
